client/booking_car_app/booking_car_app/Areas/Driver/Controllers/BookingController.cs
using booking_car_app.ApiServices.Booking;
using booking_car_app.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace booking_car_app.Areas.Driver.Controllers
{
    [Area("Driver")]
    //[Authorize(Roles = "Driver")]
    public class BookingController : Controller
    {
        private readonly IBookingService _bookingServices;
        public BookingController(IBookingService bookingService)
        {
            _bookingServices = bookingService;
        }

        public IActionResult ReceiveNotifyBooking()
        {
            ViewBag.Name = User.Identity.Name;
            var driverId = User.FindFirst("OId")?.Value;
            return View();
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> ReceiveBooking(Guid idBooking)
        //{
        //    var result = await _bookingServices.ReceiveBooking(new Entities.BookingInfo()
        //    {
        //        Id = idBooking,
        //        DriverId = User.FindFirst("OId")?.Value,
        //        Status = 2
        //    });                         
        //    return Json(new { result.Success, data = idBooking, result.Message });
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateStatusBooking(Guid idBooking, int status)
        {
            var result = await _bookingServices.UpdateStatusBooking(new Entities.BookingInfo()
            {
                Id = idBooking,
                DriverId = User.FindFirst("OId")?.Value,
                Status = status
            });
            return Json(new { result.Success, data = idBooking, result.Message });
        }

        [HttpGet]
        public async Task<IActionResult> HandleTrip(Guid id)
        {
            //ViewBag.IdBooking = id;
            var booking = await _bookingServices.GetBookingById(id);
            var data = booking.Data.ToString();
            return View(JsonConvert.DeserializeObject<BookingInfo>(data));
        }
        [HttpGet]
        public IActionResult Finish()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> DonHang()
        {
            var result = await _bookingServices.GetBookingByDriverId(User.FindFirst("OId")?.Value);
            var data = JsonConvert.DeserializeObject<List<BookingInfo>>(result.Data.ToString());
            return View(data);
        }
    }
}

client/booking_car_app/booking_car_app/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - booking_car_app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/sweetalert/sweetalert2.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">booking_car_app</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
                        </li>
                        <li class="nav-item">
                            @{
                                var role = User.FindFirst(ClaimTypes.Role)?.Value;
                            }
                            @if (role == "User")
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="DonHang">Đơn hàng</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="Driver" asp-controller="Booking" asp-action="DonHang">Đơn hàng</a>
                            }
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ChangePassword">Đổi mật khẩu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Đăng xuất</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - booking_car_app
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert/sweetalert2.all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

client/booking_car_app/booking_car_app/Views/Shared/_ManageLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>

    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/nhatnghe.css" rel="stylesheet" asp-append-version="true"/>
    <link rel="stylesheet" href="~/lib/sweetalert/sweetalert2.min.css" />
    <link href="https://cdn.datatables.net/2.0.7/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap.min.css" asp-append-version="true">
    <link rel="stylesheet" href="~/lib/smartwizard/dist/css/smart_wizard_theme_circles.min.css">
    <link rel="stylesheet" href="~/lib/smartwizard/dist/css/smart_wizard.min.css">
    <link href="~/lib/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/datatables.net-buttons-bs4/css/buttons.bootstrap4.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <div class="container-fluid">
        <header class="nn-header">
            <h1 class="nn-company">MANAGE BOOKING</h1>
            <h5 class="nn-slogan">App Booking</h5>
            <img class="nn-logo" src="~/img/header-object.png" />
        </header>

        <div class="navbar navbar-inverse">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Trang chủ</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Quản lý <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/Manage/Driver">Tài xế</a></li>                           
                            <li><a href="/Manage/Booking">Đơn hàng</a></li>
                        </ul>
                    </li>                    
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tài khoản <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/Home/Logout">Đăng xuất</a></li>
                            <li><a href="/Manage/Home/ChangePassword">Đổi mật khẩu</a></li>                           
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        <div class="nn-sheet">

            <article class="nn-body">
                @RenderBody()
            </article>

            <hr />
            <footer>
                <p>&copy; 2024 - APP BOOKING CAR</p>
            </footer>
        </div>
    </div>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/lib/datatables/datatables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap.min.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js" asp-append-version="true"></script>
    <script src="~/lib/datatables.net-bs4/js/dataTables.bootstrap4.js"></script>
    <script src="~/lib/datatables.net-buttons-bs4/js/buttons.bootstrap4.js"></script>
    <script src="~/lib/datatables.net-colreorder/js/dataTables.colReorder.js"></script>
    <script src="~/lib/datatables.net-select/js/dataTables.select.js"></script>
    <script src="~/lib/moment/moment.min.js"></script>
    <script src="~/lib/smartwizard/dist/js/jquery.smartWizard.js"></script>
    <script src="~/lib/sweetalert/sweetalert2.all.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>